name: InSituML

on:
  pull_request:
    branches: [ "khi" ]

permissions:
  contents: read

jobs:
  build:
    container: ornladios/adios2:ci-spack-ubuntu20.04-gcc11
    
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v4
    - name: Set env
      run: echo "openPMD_USE_MPI=ON" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 --statistics
    - name: Test with pytest
      run: |
        pytest
